---
title: "Qevaluation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Evaluation of model performance
```{r}
install.packages("sandwich")
library(forecast)
library(Metrics)
library(sandwich)
load("../Qforecasting/forecasts.RData")

m_DI    = cbind(forecasts$DI_h1,forecasts$DI_h3,forecasts$DI_h6,forecasts$DI_h12)
m_DI_AR = cbind(forecasts$DI_AR_h1,forecasts$DI_AR_h3,forecasts$DI_AR_h6,forecasts$DI_AR_h12)
m_AR    = cbind(forecasts$AR_h1,forecasts$AR_h3,forecasts$AR_h6,forecasts$AR_h12)
colnames(m_DI)   =c("DI_h1","DI_h3","DI_h6","DI_h12")
colnames(m_DI_AR)=c(" DI_AR_h1"," DI_AR_h3"," DI_AR_h6","DI_AR_h12")
colnames(m_AR)   =c("AR_h1","AR_h3","AR_h6","AR_h12")

# Calculates the Root Mean Square Error for each of the models
RMSE     = function(y_hat){sqrt(sum((forecasts$y - y_hat)^2)/length(y_hat))}
print("RMSE")
apply(m_DI,2,RMSE)
apply(m_DI_AR,2,RMSE)
apply(m_AR,2,RMSE)



#forecasts$dm_eDI=cbind((forecasts$DI_h1 - forecasts$y),(forecasts$DI_h3 - forecasts$y),(forecasts$DI_h6 - forecasts$y),(forecasts$DI_h12 - forecasts$y))
#colnames(forecasts$dm_eDI)   =c("Error DI_h1","Error DI_h3","Error DI_h6","Error DI_h12")


#forecasts$dm_eDI_AR=cbind((forecasts$DI_AR_h1 - forecasts$y),(forecasts$DI_AR_h3 - forecasts$y),( forecasts$DI_AR_h6 - forecasts$y),(forecasts$DI_AR_h12 - forecasts$y))
#colnames(forecasts$dm_eDI_AR)=c("Error DI_AR_h1","Error DI_AR_h3","Error DI_AR_h6","Error DI_AR_h12")

#forecasts$dm_eAR=cbind((forecasts$AR_h1 - forecasts$y),(forecasts$AR_h3 - forecasts$y),(forecasts$AR_h6 - forecasts$y),(forecasts$AR_h12 - forecasts$y))
#colnames(forecasts$dm_eAR)   =c("Error AR_h1","Error AR_h3","Error AR_h6","Error AR_h12")


forecasts$e_DI_h1 = forecasts$DI_h1    - forecasts$y
forecasts$e_DI_h3 = forecasts$DI_h3    - forecasts$y
forecasts$e_DI_h6 = forecasts$DI_h6    - forecasts$y
forecasts$e_DI_h12 = forecasts$DI_h12    - forecasts$y

forecasts$e_DI_AR_h1 = forecasts$DI_AR_h1 - forecasts$y
forecasts$e_DI_AR_h3 = forecasts$DI_AR_h3 - forecasts$y
forecasts$e_DI_AR_h6 = forecasts$DI_AR_h6 - forecasts$y
forecasts$e_DI_AR_h12 = forecasts$DI_AR_h12 - forecasts$y

forecasts$e_AR_h1    = forecasts$AR_h1    - forecasts$y
forecasts$e_AR_h3    = forecasts$AR_h3    - forecasts$y
forecasts$e_AR_h6    = forecasts$AR_h6    - forecasts$y
forecasts$e_AR_h12   = forecasts$AR_h12   - forecasts$y

print("Dm-test")
#dm_test=function(x,y){dm.test(x,y,h=1,power=1)}
#mapply(dm_test,forecasts$e_DI_h1,MoreArgs =forecasts$e_DI_AR_h1)
#dm.test(forecasts$dm_eDI,forecasts$dm_eDI_AR,h=1,power=1)

dt_DI_AR=forecasts$e_DI_h1-forecasts$e_DI_AR_h1

d_hat=1/length(forecasts$y)*sum(dt_DI_AR)
d_hat



a=lm(formula = forecasts$DI_h1~forecasts$y)
b=lm(formula = forecasts$DI_AR_h1~forecasts$y)

x=NeweyWest(a)
y=NeweyWest(b)

t.test(x,y)



apply(forecasts$dm_eDI,2,gamma_k)
#yk=function()1/length(forecasts$y)*sum((DI_AR-d)(DI_AR-d))
#dm=d/(sqrt(yk+2+sum(yk)/length(forecasts$y)))



dm.test(forecasts$e_DI_h1, forecasts$e_AR_h1, h = 1, power = 1)
dm.test(forecasts$e_DI_h3, forecasts$e_AR_h3, h = 3, power = 1)
dm.test(forecasts$e_DI_h6, forecasts$e_AR_h6, h = 6, power = 1)
dm.test(forecasts$e_DI_h12, forecasts$e_AR_h12, h = 12, power = 1)

dm.test(forecasts$e_DI_AR_h1, forecasts$e_AR_h1, h = 1, power = 1)
dm.test(forecasts$e_DI_AR_h3, forecasts$e_AR_h3, h = 3, power = 1)
dm.test(forecasts$e_DI_AR_h6, forecasts$e_AR_h6, h = 6, power = 1)
dm.test(forecasts$e_DI_AR_h12, forecasts$e_AR_h12, h = 12, power = 1)

dm.test(c(1,1,1),c(1.000001, 0.999999,1), h = 1 , power = 1)

# DM Test can't reject H_0: no statistical significant difference in the two forecasts

#MAE
MAE = function(y_hat){sum(abs(forecasts$y-y_hat))/length(y_hat)}
print("MAE")
apply(m_DI,2,MAE)
apply(m_DI_AR,2,MAE)
apply(m_AR,2,MAE)



#sMAPE
sMAPE  = function(y_hat){sum(abs(y_hat-forecasts$y)/((abs(y_hat)+abs(forecasts$y))/2))/length(y_hat)}
print("sMAPE")
apply(m_DI,2,sMAPE)
apply(m_DI_AR,2,sMAPE)
apply(m_AR,2,sMAPE)



```
