---
title: "SPL data preparation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(httr)
library(jsonlite)


#getting macroeconomic data from FRED
getJsonData = function(x){
  connection = "https://api.stlouisfed.org/fred/series/observations?"
  api_key = "&api_key=4c5743e8fb183ff3f7f47ba1ae651683&"
  file_type = "file_type=json&"
  observation_start="observation_start=1992-02-01&"
  observation_end="observation_end=2017-01-01"
  series_id=paste("series_id=",x,sep="")
  
  fromJSON(paste(connection,series_id,api_key,file_type,observation_start,observation_end, sep = ""))
}

#create time series with multiple dimensions
createFeatureMatrix = function(x){
  res = getJsonData(x[1])$observations[c("date","value")]
  res$value = as.numeric(res$value)
  res$date = as.Date(res$date)
  colnames(res) = c("date",x[1])
  
  for(i in x[2:length(x)]){
    tmp = getJsonData(i)
    res[i]=as.numeric(tmp$observations$value) 
    }
  res
}

#calculates the change, adds a zero in the front to keep vector length
getVectorPercentageChange = function(x){
  c(0,(diff(x,lag = 1)/x[1:length(x)-1]))
}

series_ids = unlist(read.csv("frednametags.csv",stringsAsFactors = FALSE))

train = createFeatureMatrix(series_ids)

train["GDAXI"] = read.csv("^GDAXI.csv")$Adj.Close
train["HSI"] = read.csv("^HSI.csv")$Adj.Close
train["N225"] = read.csv("^N225.csv")$Adj.Close
train["S&P500"] = read.csv("sandp500.csv")$Adj.Close

train[2:length(train)] = apply(train[,2:length(train)],2,getVectorPercentageChange)

#center and scale
scaledtrain = scale(train[,-1])
train[,-1] = scaledtrain
train

save(train, file="data.RData")
```

