---
title: "Qprepare"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(gridExtra)
library(reshape2)

load("../Qload/data.RData")
#check for NA values
any(is.na(train))

colnames(train)
#compare some data 
tmp = train[,c("date","INDPRO","S&P500","GDAXI","MANEMP")]
testy = melt(tmp,measure.vars=colnames(tmp[-1]))

unpreparedplot = ggplot(data=testy, aes(x=date,y=value,colour=variable,linetype=variable))+geom_line(size=1)+ ggtitle("Unprocessed") + scale_y_log10() + theme(panel.background = element_rect(fill = 'transparent', colour = 'transparent'))

pdf(file = "InitialDataPlot.pdf",width=12,height=6,paper='special') 
unpreparedplot
dev.off()

unpreparedplot = unpreparedplot +theme(legend.position="none")
unpreparedplot
#check for outliers visually
boxplot(train[,-1],varwidth=TRUE)

#since this is macroeconomic data and all outliers are explainable by events or legislations (which can be treated as events as well)
#data will be centered and scaled so no variable will have a bigger impact than another
```

```{r}
#Dickey Fuller Test

criticalValues = qnorm(c(.01,.05,.1)/2)

dickey = function(x){
  #get change values
  y = diff(train[,x])
  lag=1
  #yt-1
  yt_1 =embed(y,lag+1)[,1]

  #get lagged values
  ylagged=train[,x][(lag+1):length(y)]
  #deltaYt-1
  deltaYt_1 = embed(y,2)[,2]
  
  #apply linear model to find out if regression coefficient is 1
  res = summary(lm(yt_1~0+ylagged+deltaYt_1 ))
  #can we reject that regression coefficient is 1?
  res$coefficients[1,3] < criticalValues[1]
}

seriesDetails$dickeyres = sapply(colnames(train[,-1]),dickey)

```

```{r}
library(dplyr)
library(data.table)

#Define which preprocessing step should be done for the time series
#This is based on the appendix of the paper and on the authors choices of what to apply

seriesDetails$preparation = case_when(
  seriesDetails$units %in% c("3-Month Annualized Percent Change","Percent","Percent Change at Annual Rate","Percent of Capacity" ) ~ "Nothing",
  grepl("Nonsupervisory Employees: Manufacturing",seriesDetails$title) ~ "Nothing",
  grepl("Trade Balance", seriesDetails$title) ~ "First Difference",
  grepl("Consumer Price",seriesDetails$title) ~ "Second Difference of Logarithm",
  grepl("Hourly Earnings", seriesDetails$title) ~ "Second Difference of Logarithm",
  grepl("Index",seriesDetails$units) ~ "First Difference of Logarithm",
  grepl("Thousands",seriesDetails$units) ~"First Difference of Logarithm",
  seriesDetails$units %in% "Millions of Dollars" ~ "First Difference of Logarithm",
  grepl("Personal Consumption",seriesDetails$title) ~ "First Difference of Logarithm",
  TRUE ~ "Second Difference of Logarithm"
)

dt = as.data.table(seriesDetails)
setindex(dt, "id")




firstDifferenceLog = function(x){
  tmp = diff(log(x), lag = 1)
  tmp[-1]
}

secondDifferenceLog = function(x){
  tmp = diff(log(x), lag = 1, differences = 2)
  tmp
}




prepare = function(data,lookup){
  tmp = data[,-1]
  
  res = sapply(colnames(tmp), function (x) if(lookup[id %in% x]$preparation == "First Difference of Logarithm"){
    firstDifferenceLog(tmp[,x])
  }else{
    if(lookup[id %in% x]$preparation == "Second Difference of Logarithm"){
      secondDifferenceLog(tmp[,x])
    }else{
      if(lookup[id %in% x]$preparation == "First Difference"){
        diff(tmp[,x],lag=1)[-1]
      }else{
        tmp[,x][-c(1,2)]
      }
      
    }
  })
  data=data[-c(1,2),]
  data[,-1] = res
  data
}

trainprepared = prepare(train,dt)

#check if there is any time series that fails the dickey fuller test
any(sapply(colnames(trainprepared[,-1]),dickey)==TRUE)

tmp = trainprepared[,c("date","INDPRO","S&P500","GDAXI","MANEMP")]
testy2 = melt(tmp,measure.vars=colnames(tmp[-1]))

differencedloggedplot = ggplot(data=testy2, aes(x=date,y=value,colour=variable,linetype=variable))+geom_smooth(fill=NA, span=0.1)+ ggtitle("After logarithm and differencing") + theme(panel.background = element_rect(fill = 'transparent', colour = 'transparent'),legend.position="none")
```

```{r}
#center and scale
unscaled_train = trainprepared
scaledtrain = trainprepared
scaledtrain[,-1]=sapply(trainprepared[,-1],scale)

save(scaledtrain, file="prepareddataSC.RData")
save(unscaled_train, file = "prepareddata.RData")

tmp = scaledtrain[,c("date","INDPRO","S&P500","GDAXI","MANEMP")]
testy3 = melt(tmp,measure.vars=colnames(tmp[-1]))

scaledplot = ggplot(data=testy3, aes(x=date,y=value,colour=variable,linetype=variable))+geom_smooth(fill=NA, span=0.1)+ ggtitle("After centering and scaling") + theme(panel.background = element_rect(fill = 'transparent', colour = 'transparent'))



pdf(file = "comparisonAfterPrep.pdf",width=12,height=6,paper='special') 
grid.arrange(
  grobs = list(unpreparedplot,differencedloggedplot,scaledplot),
  widths = c(2.1, 1, 1),
  layout_matrix = rbind(c(1, 2, 2),
                        c(3, 3, 3))
)
dev.off()
```