---
title: "Qpca"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library("MASS")
library("xts")
load("../Qprepare/prepareddata.RData")
load("../Qprepare/prepareddataSC.RData")

# first row of train only contains zeros!
train = unscaled_train

# Format data into POSIXct 
train[,1] = as.POSIXct(train[,1])
dates = train[,1]

# probably unnecessary!!!
end_date = as.POSIXct("2015-01-01 01:00:00 CET")
last_known_data = which(dates == end_date)-1
origin = "1970-01-01 00:00:00"

x_raw = xts(train[,-1], order.by = train[,1])
# Only use data until december 2014 to select the model
x.sample = x_raw['/2014-12-01']
y.sample = (x.sample$`S&P500`)


#Extract PCAs
pca_data = prcomp(x.sample,
                  center = T,
                  scale. = T)

summary(pca_data)
plot(pca_data, type = "l")

diff_index = xts(pca_data$x[,1:5], order.by = dates[1:273])

save(diff_index, file = "diff_index.RData")
save(x.sample, file = "x.sample.RData")
save(y.sample, file = "y.sample.RData")
```
# Model Selection

```{R}
# Model selection
# provides a data.frame to store the results of the model selection process
#library("dynlm")
model_select = data.frame(t(c(0,0,0,0)))
names(model_select) = c("DF", "lags", "AR", "BIC")

for(i in 1:5){
  for(j in 1:8){
    for(l in 1:9){
      diff_2 = ifelse(i > 1,1,0) * diff_index[,2] 
      diff_3 = ifelse(i > 2,1,0) * diff_index[,3] 
      diff_4 = ifelse(i > 3,1,0) * diff_index[,4] 
      diff_5 = ifelse(i > 4,1,0) * diff_index[,5]
      ar_y = ifelse(l < 2, 0, 1) * y.sample
     
      model = lm(y.sample ~ lag(diff_index[,1],k=c(1:j)) + 
                            lag(ar_y, k=c(1:(l-1))) +
                            lag(diff_2,k=c(1:j)) +
                            lag(diff_3,k=c(1:j)) +
                            lag(diff_4,k=c(1:j)) +
                            lag(diff_5,k=c(1:j)), 
                            na.action = na.omit)

      bic = BIC(model)
      # append this to dataframe
      model_select = rbind(model_select, c(i,j,(l-1), round(bic,2)))
    }
  }
}
# print the full line of the optimal DI model
DI_model_select = model_select[which(model_select$BIC == min(model_select[model_select$AR == 0,"BIC"])),]
DI_model_select

# print the full line of the optimal DI-AR model
DI_AR_model_select = model_select[which(model_select$BIC == min(model_select[model_select$AR > 0,"BIC"])),]
DI_AR_model_select

```

# Forecasting
```{R}

predictions = data.frame(t(c(0,0,0,0)))
names(predictions) = c("date", "y_hat_DI", "y_hat_DI_AR", "y_hat_AR")
h = 1


# put everything in the parentheses {} into a function and then sapply (0:23) over the function 
for(i in (0:23)){
  # get diffusion indexes and estimate model
  x = x_raw[1:(last_known_data +i),] 
  y = x$`S&P500`
  pca_data = prcomp(x,
                  center = T,
                  scale. = T)
  diff_index = xts(pca_data$x[,1:5], order.by = dates[1:(last_known_data +i)] )
  
  dat = data.frame(date=index(diff_index), coredata(lag(diff_index[,1], k =1)))
  dat$y = y
  dat$y_lag1 = lag(y, k =1)
  dat_new = data.frame(date=dates[(last_known_data +i+1)], tail(diff_index[,1], n = 1),y=NA, y_lag1=tail(dat$y, n = 1), row.names = last_known_data+i+1)
  dat = rbind(dat,dat_new)
  DI_model = lm(y ~ PC1, data=dat[1:(last_known_data +i),])
  DI_AR_model = lm(y ~ PC1 + y_lag1, data= dat[1:(last_known_data +i),])
  AR_model = lm(y ~ y_lag1, data= dat[1:(last_known_data +i),])
  
  # make 1-step ahead prediction for new data
  y_hat_DI =  predict(DI_model, newdata = tail(dat, n=1))
  y_hat_DI_AR =  predict(DI_AR_model, newdata = tail(dat, n=1))
  y_hat_AR = predict(AR_model, newdata = tail(dat, n=1))
  
  predictions[i+1,] = c(date=dates[(last_known_data +i+1)], y_hat_DI , y_hat_DI_AR, y_hat_AR)
}

predictions[,1] = as.POSIXct(predictions[,1], origin = origin)



z = predictions[1:23,]
z$y = as.numeric(y["2015-01-01/"])

{plot(z$date, z$y)
points(z$date, z$y_hat_DI, pch=1, ,col ="red")
points(z$date, z$y_hat_DI_AR, pch=2, ,col ="blue")
points(z$date, z$y_hat_AR, pch=3, ,col ="green")}
z
# RMSE
RMSE = sum(sqrt((z$y - z$y_hat_DI_AR)^2)) /length(z$y_hat_DI_AR)
RMSE
sum(sqrt((z$y - z$y_hat_AR)^2)) /length(z$y_hat_AR)

```